### ISSUE TITLE
bot not working

### ISSUE THREAD

**Issue by ashramwen** [CapsLock-Studio/tg-image-captcha-bot#2]
我已經將 bot 加入群組並且賦予 admin 權限，但是還是無法運作
有新使用者透過連結還是可以直接進入
請問有使用教學嗎?

另外想透過 paypal 捐款也一直失敗

**Comment by michael34435** [comment]
牧羊犬加入要給 Delete Messages以及Ban Users才會正常

關於PayPal捐款好像本來就一直有問題 😂 台灣收款好像會失敗的樣子，有在想是不是應該透過綠界收卡，但是綠界需要營業(販賣)證明，這部份一直還沒處理

**Comment by ashramwen** [comment]
> 牧羊犬加入要給 Delete Messages以及Ban Users才會正常

這兩個都加了啊，但還是能自由進出
![image](https://user-images.githubusercontent.com/3334950/78212862-94bc7b80-74e3-11ea-9a14-539bec6c4607.png)

**Comment by michael34435** [comment]
請問是supergroup嗎

**Comment by ashramwen** [comment]
supergroup 是什麼?
只是一個普通的 group

**Comment by michael34435** [comment]
https://telegram.how/2016/03/15/supergroups02

關於supergroup的說明可以參照這個，他是一種特殊群組，牧羊犬現在只能在supergroup使用

**Comment by ashramwen** [comment]
原來如此
感謝解答
